### ISSUE TITLE
shell_manager not correctly configured

### ISSUE THREAD

**Issue by al3xfulton** [picoCTF/picoCTF#101]
After update to os shell_manager executable never makes it the expected location of  `/usr/local/bin/shell_manager` and is therefore no longer in the PATH and cannot be easily run. Vagrant appears to still provision and deploy using direct path.

**Comment by hiliang-cmu** [comment]
All  picoCTF python executables are now wrapped in a virtualenv, which needs to be activated with a command line (`source /picoCTF-env/bin/activate`).

Thinking about it though, I'm a bit hesitant to activate it automatically for user `vagrant` on login since  any future runs of vagrant/ansible tasks may be caught in that, which would be undesirable and likely incompatible. 

Thoughts @maverickwoo  ?

**Comment by maverickwoo** [comment]
(We have discussed on Discord and I am typing this here for reference.)

The solution I propose is to enable the virtual env for only interactive logins. This can be done in the `.bashrc` or equivalent of the `vagrant` user and other users that benefit from having `python3` being the same interpreter as in the picoCTF virtual env.

**Comment by maverickwoo** [comment]
@al3xfulton:

#106 has been merged and https://github.com/picoCTF/picoCTF/pull/106/files#diff-6d3a8b7214a2af43390ca760c463a76f explicitly creates `/usr/local/bin/shell_manager` as a symlink to the correct script in the virtualenv. Does this change resolve the current issue from your operational perspective, assuming the documentation is clarified in a future PR?

Thanks!

**Comment by carlislemc** [comment]
@maverickwoo @al3xfulton - yes, I think a soft link at /usr/local/bin/shell_manager pointing to /picoCTF-env/bin/shell_manager fixes the issue.

**Comment by maverickwoo** [comment]
OK, I am closing the issue. Thanks!
