### ISSUE TITLE
 shell_manager package_and_deploy

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#111]
Looking at: picoCTF-2018-problems-af/packaged-problems/forensics/meta-material, this tries to install libimage-exiftool-perl using the following in problem.json:
  "pkg_dependencies" : ["libimage-exiftool-perl"]

Unfortunately, this dependency isn't installed until later, so if you do:

sudo shell_manager package .
sudo dpkg -i picoctf-truly-an-artist-p1-0-0.deb

dpkg fails, because libimage-exiftool-perl isn't installed yet.

sudo apt-get install -f
will fix this, but it would be nice to have this happen more automatically.

**Comment by maverickwoo** [comment]
After some discussion within the tech team, it seems the root cause of this problem is the use of `dpkg -i`, which was not designed to handle dependencies. Since we have upgraded the platform OS to Ubuntu 16.04, the newer `apt install` command in it can conveniently take a deb filename and it should take care of the dependencies:

https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

So perhaps the solution to this issue is to change the commands to:
```
sudo shell_manager package .
sudo apt install picoctf-truly-an-artist-p1-0-0.deb
```

Do you think that would work?

**Comment by carlislemc** [comment]
Yes, I think that would be fine. As a future enhancement, it would be nice to have a shell_manager package_and_deploy, because I never really want to just package.

**Comment by hiliang-cmu** [comment]
Updated title to reflect remaining enhancement task
