### ISSUE TITLE
Only teacher users may become classroom teachers

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#209]
The public version seems to now be broken on adding a second teacher to a classroom., always giving the error message in the title. This might be related to issue 204.

**Comment by maverickwoo** [comment]
This is more related to #169. The reason is because in the public version there is currently no way to register a teacher account yet. (The admin account is the *only* account marked as a teacher, and yet the other accounts are never marked as a teacher even if registered as such.) We will fix that later. Thanks!

**Comment by carlislemc** [comment]
BTW, this summer I was able to add teachers to an existing classroom.
