### ISSUE TITLE
AWS Deployement

### ISSUE THREAD

**Issue by rafaelmertens** [picoCTF/picoCTF#235]
Hi, I am having issues deploying the platform in AWS, would you be able to give me a hand? The documentation on the repo doesn't seem to match the deployment to AWS anymore...
Would someone be able to give me a hand?

**Comment by maverickwoo** [comment]
Yes, we would try our best to help here. Can you please briefly describe the machine inventory of your planned AWS deployment? This information would be very useful because inventory adjustment (either manual or automatic) is an important first step in an AWS deployment.

**Comment by rafaelmertens** [comment]
Hi @maverickwoo I tried to deploy it with the terraform + ansible scripts.
The terraform scripts deployed two debian VMs (picoWeb and picoShell) 
my ansible scripts were okay until where it should create the users on the mongoDB
If I disable the authentication I can create the admin user but it won't login so it fails creating the picoWeb user..

It would also be fine for me to deploy it manually if it's easier...

**Comment by rafaelmertens** [comment]
I was planning to build a CTF, I already wrote and imported some challenges locally and tested with vagrant.. it worked fine..

This should be a small event (Maximum 20 players, most of them not very experienced...)

**Comment by rafaelmertens** [comment]
Hi @maverickwoo ,
I managed to partially deploy it on AWS.. 
I am getting an error now on the Web Shell...
`
TASK [pico-web : Autoload Shell Server into web interface] ******************************************************************************************************************************************
fatal: [pico_web]: FAILED! => {
    "changed": true, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "stderr": "OpenSSH_7.6p1 Ubuntu-4, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26310\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to xxx.xxx.xxx.xxx closed.\r\n", 
    "stdout": "Authentication failed.\r\nFailed to connect to shell server.\r\n", 
    "stdout_lines": [
        "Authentication failed.", 
        "Failed to connect to shell server."
    ]
}`


Where xxx.xxx.xxx.xxx is the pico_web public IP
When I try to connect to it manually from the pico_web to pico_shell1 it works fine..
I just wonder why is this using the Public IP and not the internal IP...

Do you have any ideas what I could be doing wrong here?

**Comment by maverickwoo** [comment]
The above message suggests that the web instance is not able to ssh into the shell instance, and it is likely a correct outcome because we don't want the 3 demo problems to be loaded into the db in an AWS deployment (one of the steps below will disable this).

Here is a rundown that I would use for small AWS deployments. For simplicity, I assume there are three instances `db.yourctf.com` (db server), `shell1.yourctf.com` (shell server), and `game.yourctf.com` (web server) . I think it is safe for both `db.yourctf.com` and `game.yourctf.com` to resolve to the same IP address in DNS and so you can try to merge the work for those two instances.

1. I assume you have already started three instances of vanilla Ubuntu 16.04 in suitable security groups. The reason we have `db` as its own instance is because we want its security group to limit this instance to be accessible to only through `game`.

1. I also assume these three instances have their own elastic IPs and the DNS names `db.yourctf.com`, `shell1.yourctf.com`, and `game.yourctf.com` resolve to these IPs respectively.

1. At this point, you want to create a git reference in the git repo. I recommend having a private branch and let's call it `private`. The goal for the next few steps is for `private` to point to a commit that is ready for automatic ansible provisioning. Note that we will be running ansible "locally" from the perspective of the instances. There are several files to pay attention to.

1. Rekey the vault by executing `deploy/rekey.py ansible/group_vars/remote_aws/vault.yml`.

1. Update `ansible/group_vars/remote_aws/vars.yml` to stop automatic events:
```yaml
auto_add_shell:         False
auto_load_problems:     False
auto_start_competition: False
```

6. Update the inventory `ansible/inventories/remote_aws`. Here is an example with a made-up `db_private_ip`:

```ini
[remote_aws:children]
db
shell
web

[db]
pico_db     ansible_connection=local hostname=yourctf-db-1    ansible_host=db.yourctf.com     db_private_ip=172.31.1.1

[shell]
pico_shell1 ansible_connection=local hostname=yourctf-shell-1 ansible_host=shell1.yourctf.com db_private_ip=172.31.1.1 shell_hostname=shell1.yourctf.com

[web]
pico_web    ansible_connection=local hostname=yourctf-web-1   ansible_host=game.yourctf.com   db_private_ip=172.31.1.1 web_fqdn=game.yourctf.com
```

7. Depending on your storage type in the `db` instance, you may need to change `db_data_device` in `ansible/roles/mongodb/defaults/main.yml` to the right device, e.g., `/dev/nvme0n1p1`.

1. Modify `picoCTF-web/api/config.py` to use your own API keys (say, for email sending).

1. At this point there are up to five modified files in the `private` branch. You may have made some other changes too. Make a commit to `private` so that `private` points to the desired commit.

1. Make a bundle file by executing `./mkdeploy.sh bundle private`. It will generate the file `dist/dist.bundle`.

1. Deploy to the `db` (must happen first), `shell1`, and `game` instances by executing the bundle file as follows:

```bash
$ DEPLOY_ANSIBLE_INVENTORYNAME=remote_aws DEPLOY_ANSIBLE_LIMIT=pico_db     dist/dist.bundle push pico_db -vv
$ DEPLOY_ANSIBLE_INVENTORYNAME=remote_aws DEPLOY_ANSIBLE_LIMIT=pico_shell1 dist/dist.bundle push pico_shell1 -vv
$ DEPLOY_ANSIBLE_INVENTORYNAME=remote_aws DEPLOY_ANSIBLE_LIMIT=pico_web    dist/dist.bundle push pico_web -vv
```
Note that each deploy will ask you for the vault password interactively.

12. Visit `http://game.yourctf.com/` and register the admin account. (The first account registered on the platform is the admin account.)

1. [optional] Visit `http://shell1.yourctf.com/shell/` to confirm shell-in-a-box is working on `shell1`.

1. Install your problems in `shell1`. Your goal is to make sure `sudo shell_manager publish` shows the meta information about your problems.

1. Login as admin on `game` over the web.

1. In Management->Configuration, change the Competition URL, Competition Name, Competition Start Time and End Time.

1. In Management->Shell Server, add `shell1`:

Key | Value
-- | --
Name | shell1
Host | shell1.yourctf.com
SSH Port | 22
Username | ubuntu
Password | value of `vault_shell_admin_password_crypt_clear` in the vault
Server Number | 1
Web Protocol | HTTP

18. In the same pane, click Check Status to confirm that `game` can ssh into `shell1`. Once confirmed, click `Load Deployment`. It will load the JSON published by the shell manager on `shell1`.

**Comment by rafaelmertens** [comment]
Hi @maverickwoo 

Thank you for your help. I was able to configure everything as it should. 
I would suggest adding this guide as a deployment guide in the Repo. It really makes the steps much easier to understand.

Thanks again
