### ISSUE TITLE
Vagrant on windows fails to provision

### ISSUE THREAD

**Issue by KevinCooper** [picoCTF/picoCTF#68]
On Windows, in the `auto_configure.yml` in the `ansible\roles\pico-web\tasks` directory, the `Autoload Shell Server into web interface` task fails with the following error message:
```
fatal: [dev_web]: FAILED! => {"changed": true, "failed": true, "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1504735035.54-245467111304057/add_shell_server.py: not found\n", "stdout": "", "stdout_lines": []}
```  
  
This occurs after a clean clone from the repo.

**Comment by veryredheaded** [comment]
Having the same issue. It would be great if someone could provide a solution or workaround for this.

**Comment by maverickwoo** [comment]
I am trying to reproduce this problem, but I am currently unable to do so. Here is my setup on an essentially new Windows machine:

* 64-bit Windows 10.0.17035.1000, with hyper-v disabled
* VirtualBox 5.2.0
* Vagrant 2.0.1
* git 2.15.0.windows.1
* picoCTF 3de17f9 (current master)

`vagrant up` completed successfully after a fresh git clone and the website (192.168.2.2) runs fine. (Other than the OS version, I can easily downgrade the others if I know what is needed.)

Thanks!

**Comment by veryredheaded** [comment]
Thank you for answering and trying to reproduce the error.

I don't get an error when running `vagrant up`, but after that, when I run `vagrant provision`. And it seems that it's connected to the Shell Server (see attached screenshot): I am able to run the app in the browser, but (as the error would suggest) I can't connect to the Shell Server. Any suggestions? 
![screenshot_error_picoctf](https://user-images.githubusercontent.com/18488581/33063758-b95f15bc-cea3-11e7-8124-3c36df0c5f2c.png)

**Comment by maverickwoo** [comment]
Hmm, I have just run `vagrant provision` on my Windows setup (described above). The provisioning for the two VMs finished without error and the web service seems to be running correctly.

So far, on my Windows test machine, I performed:

1. `git clone https://github.com/picoCTF/picoCTF.git`
2. `cd picoCTF`
3. `vagrant up`

Once finished, 192.168.2.2 works as intended, including the shell server.

To test a VM reboot (as opposed to suspend & resume), I performed:

4. `vagrant halt` to stop the two VMs
5. `vagrant up --provision` to restart the VMs and ensure that the picoCTF services are running.

Once finished, 192.168.2.2 also works as intended, including the shell server.

Just to make sure that an individual `vagrant provision` works since this matches your workflow, I performed:

6. `vagrant provision` while the two VMs are already running from step 5.

Once finished, 192.168.2.2 also works as intended, including the shell server.

If you have time, do you mind doing a `vagrant destroy` to erase the two VMs, and then carry out the 6 steps above in order, stop at the first failure, and show us the output? My guess is it will fail in step 5, showing essentially your screenshot above. Meanwhile, I will need to locate a Windows 7 machine and that will take some time and luck... :)

**Comment by veryredheaded** [comment]
@maverickwoo, I just ran `vagrant destroy` and after that completely removed the cloned repo and then cloned it again. The same error occurs now right away - when running `vagrant up`.

Won't post a screenshot again because the output is identical :( 
`TASK [pico-web : Autoload Shell Server into web interface] *********************
fatal: [dev_web]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
`

Do you think that this has something to do with the Firewall? Or any network-related settings? I'm asking this because I'm using the company's machine (I'm doing a survey on CTF platforms). 

Another reason I can think of would be that maybe the versions of required tools (VirtualBox+extension packages, Vagrant and Git) have some compatibility issues with the config of your repo... 

What else can I try to make it work? It's really frustrating :(

And thank you again for trying to help!

**Comment by maverickwoo** [comment]
Thank you very much for your patience and your description. I think now I know what the problem is and I was able to reproduce the problem on my Windows setup. The problem is that many Windows git installations perform an automatic crlf conversion at checkout. This breaks Unix shell scripts that [specify the interpreter](https://en.wikipedia.org/wiki/Shebang_(Unix)) due to the extra `\r` and `add_shell_server.py` is just one of the many scripts that get broken at clone time. 

When you have time, can you please try the following to get a fresh clone that uses the Unix line-endings?

1. `rd /s picoCTF` to completely erase your current clone
2. `git clone -c core.autocrlf=false https://github.com/picoCTF/picoCTF.git`

Afterwards, you can proceed to execute the usual commands like `cd picoCTF` and `vagrant up` etc.

**Comment by iltmri** [comment]
Hello,

I am having this same issue on Ubuntu server; have tried everything listed here on both Windows and Linux OS with no luck. It does look like there's something wrong when the add_shell_server.py runs and it cannot import api at the top of the file. Any ideas?
