### ISSUE TITLE
No register option

### ISSUE THREAD

**Issue by sestilic** [picoCTF/picoCTF#87]
Hi, trying to follow the quick start I'm able to do steps 1-4 successfully, but there is no option to register an account. I get "Welcome to nginx on Debian!

If you see this page, the nginx web server is successfully installed and working on Debian. Further configuration is required."

**Comment by maverickwoo** [comment]
This is likely the same root cause as #63 (although the title of that issue is a bit inaccurate).

The current design of a deployment of this repo *from a fresh state* is (fresh means no VM has been created at all):

1. `vagrant up` (which will by default also perform provisioning)
[do things with the VMs as desired]
2. `vagrant suspend` (to save the VM states, say before a host reboot)
3. `vagrant resume`

Now if something goes wrong in the provisioning in step 1 (`vagrant up`), or if the VMs had been powered off, vagrant will skip over the provisioning a subsequent `vagrant up` because vagrant thinks provisioning has been done on the VMs. Based on your comment in #51, this seems likely.

The solution would be to perform a provisioning on the VMs. You can either:
a. `vagrant provision` if the two VMs are already running, or
b. `vagrant up --provision` if the two VMs have been powered off (this forces vagrant to provision).

Please let us know if this solves your problem.

P.S. We are working on updating README.md to make the procedure less confusing. Sorry!

P.P.S. I think I may know the reason why the original designer do things this way: it may have to do with coping with libc offset updates in an `apt-get dist-upgrade`.

**Comment by sestilic** [comment]
Thank you! I was originally trying the setup steps while on my organization's VPN; trying it again without the VPN I am able to setup and log in correctly.
